VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fedora-serv.box"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  config.vm.define "app1" do |app|
    # app.vm.hostname = "orc-app1.test"   # <-- удалить
    app.vm.network :private_network, ip: "192.168.60.4"
    app.vm.provision "shell", inline: "sudo hostnamectl set-hostname orc-app1.test"
  end

  config.vm.define "app2" do |app|
    app.vm.network :private_network, ip: "192.168.60.5"
    app.vm.provision "shell", inline: "sudo hostnamectl set-hostname orc-app2.test"
  end

  config.vm.define "db" do |db|
    db.vm.network :private_network, ip: "192.168.60.6"
    db.vm.provision "shell", inline: "sudo hostnamectl set-hostname orc-db.test"
  end
end