Vagrant.configure("2") do |config|
  config.vm.box = "my-debian13"
  config.ssh.insert_key = false
  #config.ssh.password = "vagrant"
  config.vm.define "host" do |h1|
    h1.vm.hostname = "host"
    h1.vm.network "public_network", ip: "192.168.88.10",
                   bridge: "Realtek PCIe GbE Family Controller"

    h1.vm.provider "virtualbox" do |vb|
      vb.name   = "host"
      vb.memory = "4098"
      vb.cpus   = 4
    end
  end
end