
- name: Создаем директорию install
  file:
    path: /home/vagrant/install   # путь к директории, которую нужно создать
    state: directory                          # гарантирует, что директория будет создана, если ее нет.

- name: Скачиваем репозиторий с zabbix 7.4
  get_url:
    url: https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian13_all.deb # Адрес ключа репозитория
    dest: /home/vagrant/install/ # Путь куда будет пакет

- name: Установка репозитория
  apt:
    deb: /home/vagrant/install/zabbix-release_latest_7.4+debian13_all.deb # установка пакета с указанного пути
    update_cache: yes

- name: Установка пакетов для zabbix-server
  ansible.builtin.apt:
    name:
      - zabbix-agent
    state: present

- name: Настроить Server и ServerActive в zabbix_agentd.conf
  ansible.builtin.lineinfile:                    # позволяет точечно изменить одну строку, не затрагивая остальное содержимое.
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^#?\s*{{ item.param }}=.*'          # ищем закомментированную или активную строку
    line: '{{ item.param }}={{ ip_zabbix_server }}'   # новая строка с нужным значением
    backrefs: no                                  # заменяем только если найдено совпадение
    backup: yes                                    # создаём резервную копию
  loop:
    - { param: 'Server' }
    - { param: 'ServerActive' }
  notify: Перезагрузка zabbix-agent                      # перезапускаем агент после изменений

- name: Включить и запустить сервисы Zabbix-Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: yes