---
- name: Установка HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Автозапуск HAProxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Добавление в конфигурационный файл haproxy.cfg нашу конфигурацию в конец файла
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    insertbefore: EOF                   # Добавляет данные в конец файла
    block: |
      listen stats # веб-страница со статистикой
              bind :888
              mode http
              stats enable
              stats uri /stats
              stats refresh 5s
              stats realm Haproxy\ Statistics

      frontend example # секция фронтенд
              mode http
              bind :8088
              default_backend web_servers

      backend web_servers # секция бэкенд
              mode http
              balance roundrobin
              option httpchk
              http-check send meth GET uri /index.html
              server s1 127.0.0.1:8888 check
              server s2 127.0.0.1:9999 check

      # 4 уровень балансировщик 
      listen web_tcp
              bind :1325
              server s1 127.0.0.1:8888 check inter 3s
              server s2 127.0.0.1:9999 check inter 3s
    marker: "# {mark} ANSIBLE MANAGED BLOCK MY Config"
    backup: yes

- name: Перезагрузка HAProxy
  service:
    name: haproxy
    state: reloaded