
- name: Указываем зашифрованные переменные логин и пароль от postgresql
  include_vars:                    #  указывает на конкретный файл в папке vars самой роли
    file: pgsl_db.yml

- name: Создаем директорию install
  file:
    path: /home/vagrant/install   # путь к директории, которую нужно создать
    state: directory                          # гарантирует, что директория будет создана, если ее нет.

- name: Скачиваем репозиторий с zabbix 7.4
  get_url:
    url: https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian13_all.deb # Адрес ключа репозитория
    dest: /home/vagrant/install/ # Путь куда будет пакет

- name: Установка репозитория
  apt:
    deb: /home/vagrant/install/zabbix-release_latest_7.4+debian13_all.deb # установка пакета с указанного пути
    update_cache: yes

- name: Установка пакетов для zabbix-server
  ansible.builtin.apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.4-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
      - acl
      - python3-psycopg2
    state: present


- name: Включить и запустить сервисы Zabbix и Apache
  ansible.builtin.systemd:
    name: "{{ item }}"                # Специальная переменная цикла loop. Она принимает значение текущего элемента по очереди из списка
    enabled: yes
    state: started
  loop:                               # Цикл loop
    - zabbix-server
    - zabbix-agent
    - apache2



- name: Создание пользователя в PostgreSQL
  community.postgresql.postgresql_user:    # Специальный модуль для управления postgres
    name: "{{ postgres_db_user }}"         # переменная зашифрованная в pgsl_db.yml
    password: "{{ postgres_db_password }}" # переменная зашифрованная в pgsl_db.yml
    state: present
  become: true
  become_user: postgres                    # от имени какого пользователя идет повышение прав

- name: Создание базы данный в PostgreSQL
  community.postgresql.postgresql_db:      # Специальный модуль для управления postgres
    name: zabbix
    owner: zabbix
    encoding: UTF-8
    template: template0                    # Гарантирует, что база будет создана с чистой кодировкой
  become: true
  become_user: postgres

- name: Импорт схемы и данных в базу Zabbix
  ansible.builtin.shell:
    cmd: zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | psql zabbix
  become: true
  become_user: postgres
  register: schema_import
  changed_when: "'CREATE' in schema_import.stdout or 'ALTER' in schema_import.stdout"
  ignore_errors: true                          # Игнорируем ошибки, если таблицы уже есть
  

- name: Замена DBPassword=пароль в zabbix_server.conf
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf          # Указываем расположение
    regexp: '^#\s*DBPassword=.*'                  # Ищем закомментированную строку. Строка начинается с #, затем любое количество пробелов, затем DBPassword= и любой остаток
    line: 'DBPassword={{ postgres_db_password }}' # Заменяем строку
    backrefs: yes                                 # заменять только если regex найден
    backup: yes                                   # создать резервную копию с временной меткой перед изменением
  notify: Перезагрузка zabbix и apache2   # перезапуск только при изменении