---
- name: Смена приветствия в MOTD
  hosts: node
  become: yes
  vars_files:
    - passwords.yml  # файл с переменной для хранения пароля sudo

  vars:
    new_motd: ">>> Сервер управляется Ansible. <<<"  # Новое приветствие для MOTD обьявленное через переменную
    ansible_become_pass: "{{ sudo_pass }}" # Используем переменную из файла passwords.yml для пароля sudo

  tasks:
    - name: Отключение скриптов обновления MOTD
      ansible.builtin.file:
        path: "/etc/update-motd.d/{{ item }}" # Указываем встроенную динамическую перменную item для интерации по списку скриптов
        mode: '0644'  # Устанавливаем права на файл, что бы он не был исполняемым
      loop:  # Используем цикл для итерации по списку скриптов, которые обновляют MOTD
        - 00-header
        - 10-help-text
        - 50-motd-news
        - 60-unminimize
        - 91-release-upgrade
        - 92-unattended-upgrades

    - name: Создаем свое приветствие для MOTD
      ansible.builtin.copy:
        dest: /etc/update-motd.d/99-ansible-motd
        mode: '0755' # Делаем его исполняемым, что бы он мог выводить приветствие при входе в систему
        content: |
          #!/bin/bash
          echo "{{ new_motd }}" # Используем переменную приветстврия для вывода в MOTD