Vagrant.configure("2") do |config|
  config.vm.box = "my-debian13"
  config.ssh.insert_key = false
  #config.ssh.password = "vagrant"
  config.vm.define "RabbitMQ" do |h1|
    h1.vm.hostname = "RabbitMQ"
    h1.vm.network "public_network", ip: "192.168.88.10",
                   bridge: "Realtek PCIe GbE Family Controller"

    h1.vm.provider "virtualbox" do |vb|
      vb.name   = "RabbitMQ"
      vb.memory = "8192"
      vb.cpus   = 4
    end

    # Provision внутри блока define, чтобы переменные разрешались на ВМ, а не на хосте.
    h1.vm.provision "shell", inline: <<-'SHELL'
      echo "1. Настройка официального репозитория Docker..."
      apt-get update
      apt-get install -y ca-certificates curl gnutls-bin openssl nano

      # Добавляем GPG ключ
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

      # Формируем sources-файл (теперь переменные разрешатся на ВМ)
      echo "Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc" > /etc/apt/sources.list.d/docker.sources

      echo "2. Установка Docker Engine и Compose Plugin..."
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      usermod -aG docker vagrant
    SHELL
  end
end