---
- name: Создаем группу prometheus
  group:
    name: prometheus
    state: present
    system: yes

- name: Создаем пользователя prometheus
  user:
    name: prometheus
    group: prometheus
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    state: present


- name: Создаем папку для загрузки Prometheus
  file:
    path: /tmp/install/
    state: directory

- name: Скачиваем репозиторий
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.53.5/prometheus-2.53.5.linux-amd64.tar.gz
    dest: /tmp/install/

- name: Распаковка Prometheus
  unarchive:
    src: /tmp/install/prometheus-2.53.5.linux-amd64.tar.gz
    dest: /tmp/install/
    remote_src: yes
    list_files: yes
  register: archive_result

- name: Показать распакованные файлы
  debug:
    var: archive_result

- name: Копируем бинарные файлы prometheus и promtool
  copy:
    src: "/tmp/install/prometheus-2.53.5.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Создаем папку /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'


- name: Создаем папку /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'


- name: Копируем бинарные папки consoles и  console_libraries и файл prometheus.yml
  copy:
    src: "/tmp/install/prometheus-2.53.5.linux-amd64/{{ item }}"
    dest: /etc/prometheus/
    owner: prometheus
    group: prometheus
    remote_src: yes
  loop:
    - consoles
    - console_libraries
    - prometheus.yml
  register: etc_prometheus

- name: Посмотреть содержимое каталога с правами через ls
  shell: ls -Fla /etc/prometheus
  register: ls_output

- name: Вывести результат
  debug:
    var: ls_output

- name: Создаем сервис prometheus.service
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
    owner: root
    group: root
  notify: reload systemd

- name: Включить и запусить службу prometheus.service
  systemd:
    name : prometheus.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Добавляем прослушку Node Exporter
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
    owner: prometheus
    group: prometheus
  notify: reload systemd