---
- name: Создаем директорию http1 и http2 и http3
  file:
    path: "/home/vagrant/{{ item }}"
    state: directory
  loop:
    - http1
    - http2
    - http3

- name: Создаем файл index.html в директории http1
  copy:
    content: "Server 1 :8888"
    dest: /home/vagrant/http1/index.html

- name: Создаем файл index.html в директории http2
  copy:
    content: "Server 2 :9999"
    dest: /home/vagrant/http2/index.html

- name: Создаем файл index.html в директории http3
  copy:
    content: "Server 3 :7777"
    dest: /home/vagrant/http3/index.html

- name: Запускаем сервер на порту 8888
  shell: |
    nohup python3 -m http.server 8888 --directory /home/vagrant/http1/ --bind 0.0.0.0 > /tmp/server8888.log 2>&1 &
  args:
    executable: /bin/bash

- name: Запускаем сервер на порту 9999
  shell: |
    nohup python3 -m http.server 9999 --directory /home/vagrant/http2/ --bind 0.0.0.0 > /tmp/server9999.log 2>&1 &
  args:
    executable: /bin/bash

- name: Запускаем сервер на порту 7777
  shell: |
    nohup python3 -m http.server 7777 --directory /home/vagrant/http3/ --bind 0.0.0.0 > /tmp/server7777.log 2>&1 &
  args:
    executable: /bin/bash

- name: Даем время на запуск серверов
  pause:
    seconds: 5

- name: Проверка работы серверов
  uri:
    url: "http://127.0.0.1:{{ item }}"
    status_code: 200
    return_content: yes
  loop:
    - 8888
    - 9999
    - 7777
  register: server_check

- name: Выводим результат проверки серверов
  debug:
    msg: "Сервер на порту {{ item.item }} вернул: {{ item.content }}"
  loop: "{{ server_check.results }}"