- name: Проверим, что cookie с мастера успешно получен
  assert:
    that:
      - hostvars['localhost']['rabbitmq_master_cookie'] is defined
    fail_msg: "Cookie мастера не были получены. Проверь инвентарь и доступность мастер-ноды."

- name: Остановка службы RabbitMQ на worker ноде перед изменением cookie
  systemd:
    name: rabbitmq-server
    state: stopped

- name: Копирование cookie с мастера на worker Ноду с правами 400
  copy:
    content: "{{ hostvars['localhost']['rabbitmq_master_cookie'] }}"
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: '0400'

- name: Запуск службы RabbitMQ на worker после изменения cookie
  systemd:
    name: rabbitmq-server
    state: started

- name: Остановка приложения внутри RabbitMQ на worker для кластеризации
  command: rabbitmqctl stop_app

- name: Сброс состояния ноды для корректного присоединения к кластеру
  command: rabbitmqctl reset

- name: Присоединение worker к кластеру
  command: "rabbitmqctl join_cluster rabbit@{{ hostvars[groups['master'][0]]['ansible_hostname'] }}"

- name: Запуск приложения внутри RabbitMQ на worker после присоединения к кластеру
  command: rabbitmqctl start_app