#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
- name: Установить пакет apache2
  ansible.builtin.apt:
      name: apache2
      state: present
      update_cache: yes



- name: Скопировать файл index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart apache2

- name: Аатозапуск apache2
  ansible.builtin.service:
      name: apache2
      state: started
      enabled: true

- name: Проверка доступности стандартной страницы apache2
  ansible.builtin.uri:
      url: "http://{{ ansible_default_ipv4.address }}"
      status_code: 200

