---
# - name: Установка nginx
#   hosts: host_proxy
#   become: yes

#   roles:
#     - nginx


- name: Установка python3 сервер
  hosts: host_proxy
  become: yes

  roles:
    - server_python

- name: Установка HAProxy
  hosts: host_proxy
  become: yes
  roles:
    - haproxy
