Vagrant.configure("2") do |config|
   # Образ виртуальной машины
  config.vm.box = "my-debian13"

  # если выставлен в false, то vagrant не будет автоматически создавать и использовать собственные SSH ключи
  config.ssh.insert_key = false

  # Настройка виртальной машина host1
  config.vm.define "host1" do |h1|
   h1.vm.hostname = "host1"
  # Настройка сети
  h1.vm.network "public_network", ip: "192.168.88.50", bridge: "Realtek PCIe GbE Family Controller"
  # Настройка провайлдера и параметров ВМ
  h1.vm.provider "virtualbox" do |vb|
    vb.name= "host1"
    vb.memory = "4096"
    vb.cpus = 4
  end
  end

end