Vagrant.configure("2") do |config|
   # Образ виртуальной машины
  config.vm.box = "my-debian13"

  # если выставлен в false, то vagrant не будет автоматически создавать и использовать собственные SSH ключи
  config.ssh.insert_key = false

  # Настройка виртальной машина Zabbix Server
  config.vm.define "prometheus" do |server|
   server.vm.hostname = "prometheus"
  # Настройка сети
  server.vm.network "public_network", ip: "192.168.88.53", bridge: "Realtek PCIe GbE Family Controller"
  # Настройка провайлдера и параметров ВМ
  server.vm.provider "virtualbox" do |vb|
    vb.name= "prometheus"
    vb.memory = "4096"
    vb.cpus = 4
  end
  end

end