#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 1AAAAC3NzaC1lZDI1NTE5AAAAIDJjc5SSGkwNKl95lf/1UpgqRKOSyJN9UnSOsWCOqxIQ alex@de13
