- name: Установка пакетов для Postgres
  apt:
    name:
      - wget
      - curl
      - postgresql-common
      - ca-certificates
      - gnupg
    state: present          # гарантирует, что пакеты будут установлены, если их нет.


- name: Создаем директорию pgdg
  file:
    path: /usr/share/postgresql-common/pgdg   # путь к директории, которую нужно создать
    state: directory                          # гарантирует, что директория будет создана, если ее нет.
    owner: root                               # владелец директории
    group: root                               # группа директории
    mode: '0755'





- name: Добавление ключа репозитория Postgres
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc # Адрес ключа репозитория
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc # Путь куда будет сохранен ключ
    mode: '0644' # права доступа к файлу ключа
    owner: root
    group: root
    validate_certs: yes # проверка ssl сертификата при запуске ключа


- name:  Добавить репозиторий PGDG
  apt_repository:
    #  repo Указывает путь к скачанному ключу и url репозитория, который будет добавлен в систему
    #  {{ ansible_distribution_release }} - это переменная Ansible, которая автоматически подставляет кодовое имя текущего релиза операционной системы (например, buster для Debian 10 или focal для Ubuntu 20.04).
    repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg.list # имя файла, который будет создан в директории /etc/apt/sources.list.d/  для хранения информации о новом репозитории
    update_cache: yes # обновления кэша после добавления репозиторория


- name: Установка PostgresSQL
  apt:
    name: "postgresql-{{ postgresql_version }}" # установка пакета с указания версии которая указана в переменой в папке vars
    state: present
