groups: # Список групп
- name: netology-test # Имя группы
  rules: # Список правил текущей группы
  - alert: InsanceDown # Название текущего правила
    expr: up == 0 # Логинческое выражение
    for: 1m # Сколько ждать отбоя сработки перед отправкой оповещения
    labels:
      severity: critical # критические события
    annotations: # Описание
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down  for more than 1 minute.' # полное Описание алерта
      summary: Instance {{ $labels.instance }} down # краткое описание алерта