---
- name: Установка PostgreSQL и zabbix-server
  hosts: zabbix-server
  become: yes

  roles:
    - postgresql
    - zabbix_server

- name: Установка zabbix-agent
  hosts: zabbix-agent
  become: yes

  roles:
    - zabbix_agent