Vagrant.configure("2") do |config|

  # Настройка виртальной машина Zabbix Server
  config.vm.define "zabix-server" do |zabbix|
  # если выставлен в false, то vagrant не будет автоматически создавать и использовать собственные SSH ключи
  zabbix.ssh.insert_key = false
  # Настройка виртуальной машины
  zabbix.vm.box = "my-debian13"
  zabbix.vm.hostname = "zabbix-server"
  # Настройка сети
  zabbix.vm.network "public_network", ip: "192.168.88.50", bridge: "Realtek PCIe GbE Family Controller"
  # Настройка провайлдера и параметров ВМ
  zabbix.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end
  # Настройка провижинка для настройки Ansible
  #  zabbix.vm.provision "ansible" do |ansible|
  # ansible.playbook = "playbook.yaml"
  #  ansible.inventory_path = "inventory.ini"
  #  end
  end
end