---
# - name: Установка RabbitMQ
#   hosts: all
#   become: true
#   roles:
#     - rabbitmq


# - name: Установка pika и копирования скриптов на сервер
#   hosts: all
#   become: true
#   roles:
#     - pika


- name: Сборка и присоединение кластера RabbitMQ
  hosts: all
  become: true
  roles:
    - rabbitmq_cluster