[bastion]
bastion ansible_host=51.250.77.87

[webservers]
web-a ansible_host=10.0.1.31
web-b ansible_host=10.0.2.15

[prometheus]
prometheus-b ansible_host=10.0.2.19

[grafana]
grafana-a ansible_host=93.77.184.91

[elasticsearch]
elasticsearch-a ansible_host=10.0.1.21

[kibana]
kibana-a ansible_host=51.250.70.52

# Группы-объединения для плейбука
[monitoring:children]
prometheus
grafana

[search:children]
elasticsearch
kibana

# Группа только для приватных хостов, которым нужен ProxyJump через Бастион
[private_nodes:children]
webservers
prometheus
elasticsearch

# Переменные только для ВМ в приватных подсетях
# Первый ключ - автоматический прием новых ключей без запроса. Второй ключ - не сохранять эти временный ключи в файл ~/.ssh/known_hosts. Третий ключ - прыжок через бастион
[private_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=user@51.250.77.87'

[all:vars]
ansible_user=user
