#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Установить пакет nginx
  ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: yes



- name: Скопировать файл index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Аатозапуск nginx
  ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

- name: Проверка доступности стандартной страницы nginx
  ansible.builtin.uri:
      url: "http://{{ ansible_default_ipv4.address }}"
      status_code: 200
  register: nginx_check

- name: Вывод результата проверки
  debug:
      msg: "Nginx работает корректно, статус код: {{ nginx_check.status }}"

- name: Удалить дефолтный сайт
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx


- name: созадем файл конфигурации для нашего сайта
  template:
    src: example-http.conf.j2
    dest: /etc/nginx/conf.d/example-http.conf
    owner: root
    group: root
    mode: '0664'


- name: Создаем папку include
  file:
    path: /etc/nginx/include
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: копируем файл upstream.inc из шаблона
  template:
    src: upstream.inc.j2
    dest: /etc/nginx/include/upstream.inc
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx
